VOC = /opt/voc/bin/voc
BLD=build


all:
		mkdir -p ../../$(BLD)
		cd ../../$(BLD) && \
		$(VOC) -s \
		../dps/lists/src/lDefs.Mod \
		../dps/lists/src/strutils.Mod \
		../dps/lists/src/List.Mod \
		../dps/lists/src/StringList.Mod

tests: all
		cd ../../$(BLD) && \
		$(VOC) ../deps/lists/tst/TestList.Mod -m
		cd ../../$(BLD) && \
		$(VOC) ../deps/lists/tst/TestStrutils.Mod -m
		$(BLD)/TestStrutils
		$(BLD)/TestList

clean:
		if [ -d "$(BLD)" ]; then rm -rf $(BLD); fi
